[package]
name = "mealloc-container"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.13.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
spin.workspace = true
volatile = "0.6.1"
