[package]
name = "mealloc-conductor"
version = "0.1.0"
edition = "2021"

[dependencies]
spin.workspace = true
mealloc-container = { path = "../container" }
smallvec = "1.13.2"
tinyvec = { version = "1.8.1", features = ["tinyvec_macros"] }
